title: "Victor Ouledi — Portfolio"
description: "Data Analyst & Data Scientist — NLP, Computer Vision, Statistiques, MLOps léger."
url: "https://victorouledi.github.io"
baseurl: "/Portfolio_data_analyst_et_data_scientist_Victor_OULEDI"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

locale: fr-FR
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
timezone: Europe/Paris
